# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: snapshot

on:
  workflow_call:
    inputs:
      go_version:
        required: false
        type: string
        default: ^1
      upload_artifact:
        required: false
        type: boolean
        default: true
    secrets:
      gh_pat:
        required: false

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GH_PAT: ${{ secrets.gh_pat }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - run: |
          git config --global url."https://${{ secrets.gh_pat }}@github.com/nics-dp".insteadOf "https://github.com/nics-dp"
        if: env.GH_PAT != null
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: ${{ inputs.go_version }}
          cache: true
          check-latest: true
      - uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: latest
          distribution: goreleaser
          args: release --clean --snapshot --skip=sign,sbom
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ inputs.upload_artifact == true && always() }}
        with:
          retention-days: 7
          name: dist
          path: |
            dist
