#!/usr/bin/env bash
#MISE description="Enrich SBOM with ecosystem metadata"
#MISE hide=true
#MISE depends=["sbom:source"]
#MISE silent="stdout"
#MISE tools={"github:snyk/parlay"="0.11.0"}

parlay ecosystems enrich sbom-source.cdx.json > enriched-source.cdx.json
