#!/usr/bin/env bash
#MISE description="Run bandit SAST scanner"
#MISE hide=true
#MISE raw=true

set -euo pipefail
# shellcheck disable=SC1091
source "$(dirname "$0")/../lib/py-env"

"${PY_RUNNER_ARR[@]}" bandit -r "$PY_BANDIT_PATHS" --exclude "$PY_BANDIT_EXCLUDE"
