[settings]
jobs = 16
task.output = "keep-order"
unix_default_inline_shell_args = "bash -c"

# ------------------------------------------------------------------------------
[tools]
# Bun related
bun = "latest"

# Dockerfile lint
hadolint = "latest"

# SBOM generation
syft = "latest"
"github:snyk/parlay" = "latest"

# Deps vuln scanning
trivy = "latest"
grype = "latest"

# Static scanning
"pipx:semgrep" = "latest"
codeql = { version = "latest", bin_path = "codeql", platforms = """
[linux-x64]
asset_pattern = "codeql-linux64.zip"

[macos-arm64]
asset_pattern = "codeql-osx64.zip"

[macos-x64]
asset_pattern = "codeql-osx64.zip"

[windows-x64]
asset_pattern = "codeql-win64.zip"
""" }

# Docker Operation
docker-cli = "latest"
docker-compose = "latest"
"github:docker/buildx" = { version = "latest", bin = "buildx" }

# MISC
gum = "latest"

# ------------------------------------------------------------------------------
[env]  # env for mise tasks

# ------------------------------------------------------------------------------
[task_config]
includes = ["git::https://github.com/nics-dp/meta.git//.mise/tasks"]

# ==============================================================================
#  Env init Tasks
# ==============================================================================
[tasks.init]
description = "Initialize Environment"
run = ["ruler", "gs:clone", "bun install --frozen-lockfile"]

# ==============================================================================
#  Bun Tasks
# ==============================================================================
[tasks.build]
description = "Build the web app"
run = "bun run build"

[tasks.lighthouse]
description = "Run Lighthouse CI"
run = """
bun run build
bunx @lhci/cli autorun
"""

[tasks.bundle-size]
description = "Run bundle size checks"
run = """
bun run build
bunx size-limit
"""

# ==============================================================================
#  Misc Tasks
# ==============================================================================

[tasks.clean]
description = "Cleanup leftovers"
run = '''
echo "Cleaning..."
rm -rf dist
rm -rf coverage
rm -rf node_modules/.cache
echo "Clean completed!"
'''

# ==============================================================================
#  CI Tasks
# ==============================================================================
[tasks."ci:test"]
description = "Run unit tests with coverage"
run = "bun run test:coverage"

[tasks.ci]
description = "Run all CI checks"
depends = [
  "ci:commitlint",
  "ci:hadolint",
  "ci:trivy-iac",
  "ci:lint",
  "ci:typecheck",
  "ci:format-check",
  "ci:knip",
  "ci:semgrep",
  "ci:test",
]

# ==============================================================================
#  SBOM Tasks
# ==============================================================================

[tasks.sbom]
description = "Run full SBOM pipeline (generate, enrich, scan)"
depends = ["sbom:trivy", "sbom:grype"]
