# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json

name: Bug Report
description: Report a bug you're experiencing.
type: bug
body:
  - type: input
    id: tool
    attributes:
      label: Tool Name
      description: Which tool or binary is affected?

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: "Examples: `v1.2.3` / `main` / `commit 1a2b3c`"

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior

  - type: input
    id: environment
    attributes:
      label: Environment
      description: "OS / browser / runtime version / etc."
