#!/usr/bin/env bash
#MISE description="Build JS/TS frontend via bun run build"
#MISE hide=true
#MISE raw=true
#MISE silent="stdout"
#MISE tools={bun="latest"}
#MISE depends=["node:install"]

bun run build
