#!/usr/bin/env bash
#MISE description="Run commitlint on recent commits"
#MISE raw=true

bun install --no-save @commitlint/cli @commitlint/config-conventional && bunx commitlint --from HEAD~1 --to HEAD
