#!/usr/bin/env bash
#MISE description="Run unit tests with coverage and generate report"

go test -race -coverprofile=coverage.out ./...
go tool cover -html=coverage.out -o coverage.html
go tool cover -func=coverage.out > coverage.md
