#!/usr/bin/env bash
#MISE description="Run Trivy license compliance check"
#MISE hide=true
#MISE raw=true
#MISE tools={trivy="0.74.0"}

# shellcheck disable=SC1091
source "$(dirname "$0")/../lib/require-tool"
require_tool trivy
trivy fs --scanners license --exit-code 0 .
