#!/usr/bin/env bash
#MISE description="Tear down Docker Compose services (stop + remove containers/networks)"
#MISE hide=true
#MISE raw=true
#USAGE arg "[services]" var=#true var_min=0 help="Services to tear down (default: all)"
# shellcheck disable=SC2154 # usage_services is set by mise USAGE

docker compose down --remove-orphans "${usage_services[@]}"
