#!/usr/bin/env bash
#MISE description="Run go generate (code generation)"
#MISE hide=true
#MISE raw=true
#MISE depends=["go:install"]
#MISE silent="stdout"

set -euo pipefail
paths="${GO_GENERATE_PATHS:-./...}"
go generate "$paths"
